### PR TITLE
Custom shell for docker, kubectl, openshift, lxc, safe-ssh

### PR DESCRIPTION
**Pull request by dAnjou**
Tests are missing, wanted to have your input on that. IF you like this PR, that is :)

### CODE REVIEW

**Comment by dAnjou** [comment]
I force-pushed, sorry. Travis didn't catch that :/

**Comment by dAnjou** [comment]
Same as in #515, some Nagios related tests 🤔

**Comment by philpep** [comment]
Hi, what are your usages of this ?

**Comment by dAnjou** [comment]
We need a login shell to load `.profile` in Amazon Linux.

**Comment by dAnjou** [comment]
Just for completeness, I know you still wanna think about it.

**Comment by dAnjou** [comment]
Meh, closing it, some other file slipped in. I'm gonna open an issue instead.

**Pull request closed without merging**
