### PR TITLE
[dnm] testing opendev ci

### PR DESCRIPTION
**Pull request by ianw**
please ignore, just testing a fix for opendev CI job

Depends-On: https://review.opendev.org/680895

### CODE REVIEW

**Comment by ianw** [comment]
opendev seem to be having some connection issues to github for this project (https://storyboard.openstack.org/#!/story/2006498).  the job was failing due to my misconfiguration of it, i should have fixed that (https://review.opendev.org/680534).  just leaving this for debugging ATM, will remove it when complete

**Comment by philpep** [comment]
I deactivated opendev because it was failing all the PR. I re-enabled it now

**Comment by philpep** [comment]
recheck

**Comment by ianw** [comment]
Thanks ... It's been a bit of a learning curve making the job setup more generic so it runs in this context, and I have been tardy fixing it :( I will look at this failure

**Comment by ianw** [comment]
recheck

**Comment by philpep** [comment]
awesome, thanks @ianw !

**Pull request closed without merging**
