### PR TITLE
add full path to interfaces.py ip call

### LINKED ISSUE #258: ip: command not found
Hi guys. 

I'm using testinfra through molecule, and experienced a bug. It tells me ip: command not found. 

```
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
    rootdir: /home/user/git.example.de/example_project/provisioning/roles/haproxy/molecule/default, inifile:
    plugins: testinfra-1.7.1
collected 18 items                                                              
    
    tests/test_lbweb1.py FFFFF.F.
    tests/test_default.py ....
    tests/test_lbweb2.py F..F..
    
    =================================== FAILURES ===================================
    _________________ test_keepalived_on_lbweb1[ansible://lbweb2] __________________
    
    host = <testinfra.host.Host object at 0x7f2ecd47d290>
    
        def test_keepalived_on_lbweb1(host):
            interface = host.interface('enp0s8:0')
        
    >       assert "192.168.11.7" not in interface.addresses
    
    tests/test_lbweb1.py:13:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    
    self = <interface enp0s8:0>
    
        @property
        def addresses(self):
    >       stdout = self.check_output("ip addr show %s", self.name)
    E       AssertionError: Unexpected exit code 127 for CommandResult(command=u'ip addr show enp0s8:0', exit_status=127, stdout=u'', stderr=u'/bin/bash: ip: command not found')
    E       assert 127 == 0
    E        +  where 127 = CommandResult(command=u'ip addr show enp0s8:0', exit_status=127, stdout=u'', stderr=u'/bin/bash: ip: command not found').rc
    
    /home/user/.local/lib/python2.7/site-packages/testinfra/modules/interface.py:69: AssertionError
```
There are the same errors reported coming from line 60 of testinfra/modules/interface.py.

When I change the command in those lines to use the full path, the tests succeed:
```
ansible-2.3 user:~/$ sed -n -e '60p' -e '69p' /home/user/python-venv/ansible-2.3/lib/python2.7/site-packages/testinfra/modules/interface.py
        return self.run_test("/usr/sbin/ip link show %s", self.name).rc == 0
        stdout = self.check_output("/usr/sbin/ip addr show %s", self.name)
```
```
ansible-2.3 user:~/$ molecule verify
--> Test matrix
    
└── default
    └── verify
--> Scenario: 'default'
--> Action: 'verify'
--> Executing Testinfra tests found in /home/user/git.example.de/example_project/provisioning/roles/haproxy/molecule/default/tests/...
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.13, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
    rootdir: /home/user/git.example.de/example_project/provisioning/roles/haproxy/molecule/default, inifile:
    plugins: testinfra-1.7.1
collected 14 items                                                              
    
    tests/test_lbweb1.py ....
    tests/test_default.py ....
    tests/test_lbweb2.py ......
    
    ========================== 14 passed in 24.32 seconds ==========================
Verifier completed successfully.
```

When I login to the box, the command is there of course:
```
[vagrant@lbweb1 ~]$ which ip
/usr/sbin/ip
[vagrant@lbweb1 ~]$ `!!` a
`which ip` a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:91:e5:59 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 75268sec preferred_lft 75268sec
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:97:1a:db brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.5/24 brd 192.168.11.255 scope global enp0s8
       valid_lft forever preferred_lft forever

```

### PR DESCRIPTION
**Pull request by loomsen**
Fixes #258

### CODE REVIEW

**Comment by philpep** [comment]
Hello, thanks for contributing !

On my debian stretch:

```
% command -v ip
/sbin/ip
```

I think we could try do detect if ip exists in `$PATH` and if not, test against well known paths.

**Comment by loomsen** [comment]
Hi @philpep.
On modern distros /sbin should be a link pointing to /usr/sbin. At least this should be true for systemd distros. 
But to be honest, my python foo isn't strong enough to implement your suggestion, yet. I will try though :)

**Comment by loomsen** [comment]
OK, I think I found a pretty clean solution. Could you check it out please @philpep  :)

**Comment by loomsen** [comment]
Oomph, ok, that doesn't work with python 3.5 :/

**Comment by loomsen** [comment]
OK, please review. Works for me with python 2.7 and python 3.6.2.
It's rather ugly, cause I repeat myself, but I don't know how to do it differently in python. Excuse this please :)

**Comment by philpep** [comment]
Hi, nice try, thanks! However your solution has a major flaw, it should run on remote (ssh, docker) so you can rely only on remote commands.

I implemented a solution in #261 so I'm closing this one. Thanks

**Pull request closed without merging**
