### PR TITLE
Docker backend

### PR DESCRIPTION
**Pull request by philpep**
Docker backend using docker native client.

Usage: testinfra --connection=docker --hosts=debian:jessie

For each test function, testinfra will spawn a container, run function
on it, then kill and remove container.

### CODE REVIEW

**Comment by philpep** [comment]
Need to avoid `--connection=docker` without `--hosts`

**Comment by philpep** [comment]
It seem this doesn't play well with parallel execution (using pytest-xdist) on a single host.

**Comment by goodwillcoding** [comment]
I am guessing it would make sense to have the backend handle just running docker commands without start up and tear down at all (for example to test a running instance)

**Comment by philpep** [comment]
Test this please

**Comment by philpep** [comment]
retest this please

**Comment by philpep** [comment]
@goodwillcoding you're absolutely right. Also, after thinking a bit, I think launching containers it out of scope of testinfra. There are already tools for that like vagrant, kitchen and it's easy to do it in a testinfra script (by using a hook or a fixture), allowing the user to configure many things like command, exposed ports, volumes etc.

**Pull request merged**
