### PR TITLE
Add a kubectl backend

### PR DESCRIPTION
**Pull request by jesselang**
I wanted to test container deployments in Kubernetes, so I hacked together a backend. I've manually functionally tested it, but I'm not sure what kind of automated testing is desired/required, or whether you want to make Kubernetes (minikube, etc.) a test dependency. Looking for guidance on this.

I'll be happy to update the docs. Thanks!

### CODE REVIEW

**Comment by philpep** [comment]
Hi thanks ! This looks good to me. I'd be nice to add some doc (with example) in ``doc/source/backends.rst``

PS: Your PR inspired me this new feature https://github.com/philpep/testinfra/issues/159

**Comment by jesselang** [comment]
I've added the entry in the documentation. Looking forward to this getting merged. Thanks!

**Comment by jesselang** [comment]
FYI: CI is failing due to #161.

**Comment by philpep** [comment]
Merged, thanks !

**Pull request merged**
