### PR TITLE
Fixes for winrm & doc

### PR DESCRIPTION
**Pull request by philpep**
CC @gtmanfred can you review this and tell me if you're ok ?

### CODE REVIEW

**Comment by gtmanfred** [comment]
this works :+1:

**Comment by gtmanfred** [comment]
There is a bug with windows + salt

I think it was caused by using `%s` and the old string formatting.

It is escaping the `\` in the Windows path, and causing this to not work for some reason :/

```
$ bundle exec kitchen verify windows
-----> Starting Kitchen (v1.17.0)
/Users/daniel/.rvm/gems/ruby-2.4.0/bin/vagrant
-----> Verifying <vagrant-windows-2012r2>...
       [Shell] Verify on instance=#<Kitchen::Instance:0x007f8ce02e1048> with state={:hostname=>"127.0.0.1", :port=>"2200", :username=>"vagrant", :password=>"vagrant", :rdp_port=>"3389", :last_action=>"setup", :last_error=>"Kitchen::ActionFailed"}
============================= test session starts ==============================
platform darwin -- Python 3.6.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /Users/daniel/.pyenv/versions/3.6.2/bin/python3.6
cachedir: .cache
rootdir: /Users/daniel/github/kitchen-salt, inifile:
plugins: testinfra-1.6.6.dev8
collecting ... collected 10 items

tests/integration/test_git.py::test_pkg[git] SKIPPED
tests/integration/test_hidden.py::test_hidden_dirs SKIPPED
tests/integration/test_hidden.py::test_hidden_sls SKIPPED
tests/integration/test_salt.py::test_ping PASSED
tests/integration/test_salt.py::test_git_depends SKIPPED
tests/integration/test_salt.py::test_apt_depends SKIPPED
tests/integration/test_salt.py::test_postfix_depends SKIPPED
tests/integration/test_salt.py::test_spm_depends SKIPPED
tests/integration/test_salt.py::test_path_depends FAILED
tests/integration/test_user.py::test_jdoe SKIPPED

=================================== FAILURES ===================================
______________________________ test_path_depends _______________________________

salt = functools.partial(<salt>, config='c:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\etc\\salt', local=True)

    def test_path_depends(salt):
        formulas = set(['foo',])
        dirs = salt('cp.list_master_dirs')
        print(dirs)
>       assert all([formula in dirs for formula in formulas])
E       assert False
E        +  where False = all([False])

tests/integration/test_salt.py:46: AssertionError
----------------------------- Captured stdout call -----------------------------
[]
================ 1 failed, 1 passed, 8 skipped in 2.72 seconds =================
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <vagrant-windows-2012r2>.  Please see .kitchen/logs/vagrant-windows-2012r2.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by philpep** [comment]
@gtmanfred oops ! Ok I stop the release process until this is fixed (patch welcome :) )

**Comment by gtmanfred** [comment]
Yup, I am working on it now.

If I remove the `pipes.quote` from the winrm backend, it fixes it, but obviously people would have to escape spaces in their strings :/

```
diff --git a/testinfra/backend/winrm.py b/testinfra/backend/winrm.py
index 0b510d9..2ea2f4a 100644
--- a/testinfra/backend/winrm.py
+++ b/testinfra/backend/winrm.py
@@ -57,3 +57,9 @@ class WinRMBackend(base.BaseBackend):
         p.cleanup_command(shell_id, command_id)
         p.close_shell(shell_id)
         return self.result(rc, command, stdout, stderr)
+
+    @staticmethod
+    def quote(command, *args):
+        if args:
+            return command % args
+        return command
```

Would that be ok, or should I dig deeper?

**Comment by gtmanfred** [comment]
I think I have a better fix.

**Pull request merged**
