### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by trevor-viljoen**
This adds some basic support for Windows packages (chocolatey) and users. I'm not sure how to add tests for this because the Windows docker images that are available require a Windows host to run.  Also, I apologize for this in advance. We needed to be able to test some things at work, so I thought I'd see if I could add some very basic Windows support. This helps to start addressing #330, but I haven't yet worked out a solution for the file module.

### CODE REVIEW

**Comment by philpep** [comment]
Hi @trevor-viljoen , thanks for the patches !
I added some commit with minor changes, can you tell me if it still works for you ?
(especially I'm not sure about exit code for "command not found").

Then I'll be happy to merge this !

**Comment by trevor-viljoen** [comment]
I’m on holiday, but will try to check this out as soon as I can. From looking at the changes you made, I don’t see anything that should break anything. I’ll check on the error code.

**Comment by philpep** [comment]
Ok thanks!
Especially I'm not sure about exit code 127 for "command not found", otherwise the PR should work just like before my amends.

**Comment by trevor-viljoen** [comment]
@philpep Running the tests I wrote with the changes above, I get this error:
```
E       AssertionError: Unexpected exit code 1 for CommandResult(command='uname -s', exit_status=1, stdout=None, stderr=b"'uname' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
```

**Comment by philpep** [comment]
@trevor-viljoen thanks, I updated the code accordingly. I think we can do better to detect windows but I'm ok to move forward with the current code.

**Comment by trevor-viljoen** [comment]
Looks good to me. One idea to better detect Windows would be to check for `stderr`'s output. `'uname' is not recognized as an internal or external command, operable program or batch file.`

```python
if uname.rc == 1 and "batch file" in uname.stderr:
    sysinfo.update(**self._get_windows_sysinfo())
    return sysinfo
```

**Comment by trevor-viljoen** [comment]
This works for me.

```python
from packaging import version as pkgver


@pytest.mark.parametrize("name, version", [
    ("vcredist2010", "10.0.40219.2"),
])

def test_packages(host, name, version):
      """ Make sure packages are installed and correct version """
      pkg = host.package(name)
      assert pkg.is_installed
      pkg_version = pkgver.parse(pkg.version)
      assert pkg_version > pkgver.Version("10.0")

def test_user(host):
      """ Make sure vagrant user exists """
      user = host.user('vagrant')
      assert user.exists
      assert user.name == 'vagrant'
      assert 'Administrators' in user.groups
      assert 'Users' in user.groups
```

**Comment by philpep** [comment]
> Looks good to me. One idea to better detect Windows would be to check for `stderr`'s output. `'uname' is not recognized as an internal or external command, operable program or batch file.`

Yes but I'm scared the message could be internationalized with the user language here :)

The PR looks good to me, I'll merge as soon as the travis build is green.
I also opened https://github.com/philpep/testinfra/issues/429 If you have some time to spend on windows testing.

Thanks!

**Pull request merged**
