### PR TITLE
User expires and system

### PR DESCRIPTION
**Pull request by elementalvoid**
Added two methods:

1. Check for user expiration.
2. Check if account is a system account.

Tox tests pass save the password test that was failing before the changes. All code passed flake8 checks.

### CODE REVIEW

**Comment by elementalvoid** [comment]
Another push is pending. I'm adding tests for the new methods.

**Comment by elementalvoid** [comment]
Test added for expires.

However, I'm having issues with the system attribute. Debian's min and max system uids are 100 and 999 respectively. The sshd user's uid is 105. The system attribute is returning False.

I'll fix this tomorrow and push another update.

**Comment by philpep** [comment]
Hi, thanks !

The expiration look good. For the 'system' user I'd prefer a more reliable way (but not sure if it exists).

Also need to check implementation on BSDs (I can do it)

**Comment by elementalvoid** [comment]
> For the 'system' user I'd prefer a more reliable way (but not sure if it exists).

I'm not sure there is one either. Maybe a better regex against the file or some failure checking. However, it's distribution dependent what the default values are and it's customizable. You literally have no idea what the system user ids might be when you land on some *nix box.

**Comment by philpep** [comment]
Hi, I juste merged  aca298cf777de2d6d600c99f8dea6ee3af9520fb with the "account expiration" part (enhanced with BSD support, returning a datetime object and a real test).

I'll not keep the "system" account part because the way to get the information seems too weak for me (but can easily be done in a testinfra test).

I close this one. Thanks !

**Pull request closed without merging**
