### PR TITLE
LXD Backend

### PR DESCRIPTION
**Pull request by hswong3i**
Copy of LXC backend for LXD containers.

Clone from https://github.com/philpep/testinfra/pull/334

### CODE REVIEW

**Comment by hswong3i** [comment]
Ok now looks good (https://travis-ci.org/alvistack/ansible-role-ansible/jobs/534015521), with:

* Ansible >= 2.8.0
* Molecule master
* LXD container with Ubuntu 18.04

**Comment by philpep** [comment]
Hi @hswong3i , awesome, thanks for this PR !

I modified your PR with https://github.com/philpep/testinfra/pull/445/commits/15886d84ff7dce5bdcb96cd9206068dab24da79a to avoid code dupplication. Also I fixed the build on master so the travis build should be green. Can you test if it's still works for you ? I guess by restarting your travis build for alvistack/ansible-role-ansible  on this PR.
Then I'll merge this and make a new release.

Thanks!

**Comment by hswong3i** [comment]
Wow thanks @philpep ;-)
Test now revoked, see https://travis-ci.org/alvistack/ansible-role-ansible/jobs/534015521
If the test passed I will rebase the code into a single commit for your merge ;-)

**Comment by hswong3i** [comment]
@philpep CI passed and PR rebased ;-)

**Comment by philpep** [comment]
Merged, thanks!

**Comment by philpep** [comment]
Released in testinfra 3.0.4

**Pull request merged**
