### PR TITLE
[LOOKING FOR SOMEONE TO TAKEOVER :-] replace ansible base_parser with create_base_parser

### PR DESCRIPTION
**Pull request by singuliere**
As of https://github.com/ansible/ansible/pull/50069 the base_parser
function no longer exists. Use
ansible.arguments.optparse_helpers.create_base_parser
instead.

Fixes: https://github.com/philpep/testinfra/issues/401

### CODE REVIEW

**Comment by singuliere** [comment]
This is only a draft and turns out to more involved than a function name replaced with another. The argument parsing and storage moved from being methods of the CLI class and derived classes to partly static methods and in the end the resulting options is stored in a global variable instead of a data member.

**Comment by singuliere** [comment]
@philpep this is above my paygrade and I would very much appreciate your guidance on how to proceed with this change. Should I keep going in this direction or would you recommend another approach?

**Comment by decentral1se** [comment]
Looks like https://github.com/philpep/testinfra/pull/410 is another direction for a solution!

**Comment by singuliere** [comment]
@decentral1se indeed! Let's close this one then.

**Pull request closed without merging**
