### PR TITLE
Avoid JSON parsing error in get_ansible_inventory

### PR DESCRIPTION
**Pull request by ssbarnea**
Avoids Ansible bug https://github.com/ansible/ansible/issues/59973 which
prevents testinfra from parsing inventory by disabling ansible verbosity.

Fixes: #470

### CODE REVIEW

**Comment by decentral1se** [comment]
> Has someone validated that this does the job?

Asked in https://github.com/ansible/molecule/issues/2188#issuecomment-517958005.

**Comment by WojciechPolnik** [comment]
#471
with fresh `pip install -U molecule` and applied proposal `molecule verify` passed successfully.

I've tested configurations: 
- ansible 2.5, 2.6, 2.7, 2.8. 
- centos and macos OSs
- python 2.7 and 3.7.
- commands `molecule test` and `molecule verify` 

#472
Unfortunately, this proposal will not work. 
Even though it is more clear in reading user option `--output` appears to be added in ansible `2.8`. Testing with 2.5, 2.6, 2.7 returned `error: no such option: --output`

Full error: 
```bash
==================================== ERRORS ====================================
    ____________________ ERROR collecting tests/test_default.py ____________________
    tests/test_default.py:6: in <module>
        os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
    ../../../test/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:131: in get_hosts
        inventory = self.inventory
    ../../../test/lib/python3.7/site-packages/testinfra/utils/__init__.py:44: in __get__
        value = obj.__dict__[self.func.__name__] = self.func(obj)
    ../../../test/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:149: in inventory
        return get_ansible_inventory(self.ansible_config, self.inventory_file)
    ../../../test/lib/python3.7/site-packages/testinfra/utils/ansible_runner.py:62: in get_ansible_inventory
        local.check_output(cmd, *args)
    E   AssertionError: Unexpected exit code 2 for CommandResult(command=b'ansible-inventory --list --output=/var/folders/mb/ckw0hwgs00bc763q92gn6h9r0000gq/T/tmpdpl1xezo -i /var/folders/mb/ckw0hwgs00bc763q92gn6h9r0000gq/T/molecule/molecule_test_ansible_verbose/default/inventory/ansible_inventory.yml', exit_status=2, stdout=None, stderr=b'Usage: ansible-inventory [options] [host|group]\n\nansible-inventory: error: no such option: --output\n')
    E   assert 2 == 0
    E    +  where 2 = CommandResult(command=b'ansible-inventory --list --output=/var/folders/mb/ckw0hwgs00bc763q92gn6h9r0000gq/T/tmpdpl1xezo...one, stderr=b'Usage: ansible-inventory [options] [host|group]\n\nansible-inventory: error: no such option: --output\n').rc
    !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
    =========================== 1 error in 0.60 seconds ============================
```

**Comment by philpep** [comment]
Merged, thanks ! I'll release this in a new version today.

**Comment by decentral1se** [comment]
:fire: :fire: :fire:

**Comment by ssbarnea** [comment]
@philpep I am waiting for the new release to bump it in molecule. If you have concerns about the risk of breaking others you can tag it as a pre-release (`3.0.6rc1`) so normal users would not get it. I would still be able to add `testinfra>=3.0.6rc1` in molecule and consume it.

**Pull request merged**
