### PR TITLE
Add docs for winrm and salt

### PR DESCRIPTION
**Pull request by gtmanfred**
Also add flags to the options for the winrm backend can be passed from the command line

Thanks!
Daniel

### CODE REVIEW

**Comment by philpep** [comment]
I reworked some of your commits (some fixes in doc).
For options in the command line I was not satisfied because all backend options should be specified in hostspec (eg. ``winrm://user@IP?opt=val&opt2=val2``). Also I found passing password in hostspec with the syntax ``user:password@host`` is more frequent. So I added this in ``parse_hostspec``.

I pushed my code + your code in your master branch (github allow maintainer to do this) but I appears to close the PR automatically :D Looks buggy. Can you recreate your pull request based on your actual master branch ?

**Comment by gtmanfred** [comment]
ha! weird.

Can you push them again, I think I overwrote them when I did a force push :/

**Comment by philpep** [comment]
Well this seems buggy, now i've a "permission denied". I recreated the PR in #239 , sorry for confusion

**Comment by gtmanfred** [comment]
No worries!

**Comment by gtmanfred** [comment]
Hrm, fyi I did this today and it worked great.  thanks for the tip.

https://github.com/saltstack/salt/pull/43298

**Pull request closed without merging**
